[2025-07-20T18:11:40.784+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-20T18:11:40.810+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1.extract_to_s3 manual__2025-07-20T18:06:31.072756+00:00 [queued]>
[2025-07-20T18:11:40.819+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1.extract_to_s3 manual__2025-07-20T18:06:31.072756+00:00 [queued]>
[2025-07-20T18:11:40.820+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-07-20T18:11:40.839+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_to_s3> on 2025-07-20 18:06:31.072756+00:00
[2025-07-20T18:11:40.848+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=267) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-20T18:11:40.851+0000] {standard_task_runner.py:63} INFO - Started process 269 to run task
[2025-07-20T18:11:40.852+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'extract_to_s3', 'manual__2025-07-20T18:06:31.072756+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/app_dag.py', '--cfg-path', '/tmp/tmp4mlt3v8v']
[2025-07-20T18:11:40.854+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract_to_s3
[2025-07-20T18:11:40.920+0000] {task_command.py:426} INFO - Running <TaskInstance: dag1.extract_to_s3 manual__2025-07-20T18:06:31.072756+00:00 [running]> on host 75e48cf8ec49
[2025-07-20T18:11:41.062+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rofiat' AIRFLOW_CTX_DAG_ID='dag1' AIRFLOW_CTX_TASK_ID='extract_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-07-20T18:06:31.072756+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-20T18:06:31.072756+00:00'
[2025-07-20T18:11:41.064+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-20T18:11:41.066+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-20T18:11:41.066+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 15, in random_user_to_s3
    data = response.json()['results']
           ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'results'
[2025-07-20T18:11:41.081+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag1, task_id=extract_to_s3, execution_date=20250720T180631, start_date=20250720T181140, end_date=20250720T181141
[2025-07-20T18:11:41.104+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task extract_to_s3 ('results'; 269)
[2025-07-20T18:11:41.148+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-20T18:11:41.181+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-20T18:11:41.185+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
